# -*- coding: utf-8 -*-
"""ClientesBanco1_Analise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FYNVTF0m-Qj7Yix-TJtEQnSmL81KrHPD
"""

import pandas as pd
import matplotlib.pyplot as plt

# Importa o conteúdo do Google Drive
#from google.colab import drive
#drive.mount('/content/drive')

# Importar o arquivo .csv
tabela = pd.read_csv("/content/drive/MyDrive/HashtagAnaliseComPython/ClientesBanco1.csv")

# Faz o drop da Coluna (axis=1) "CLIENTNUM"
tabela = tabela.drop(["CLIENTNUM", "Idade", "Sexo", "Educação", "Estado Civil", "Faixa Salarial Anual", "Categoria Cartão"], axis=1)

display(tabela)

# Grava o arquivo com as alterações
tabela.to_csv("arquivo.csv", index=False)

display(tabela)

tabela['Categoria'] = tabela['Categoria'].map({'Cliente': 0, 'Cancelado': 1})

display(tabela)

import seaborn as sns

# Criando o gráfico
plt.figure(figsize=(16,8))
sns.heatmap(tabela.corr(), annot=True, cmap='coolwarm')

# Exibindo o gráfico
plt.show()

# Calculando a correlação das colunas em relação à coluna 'Categoria'
correlacao = tabela.corr()['Categoria'].sort_values()

# Criando o gráfico de barras horizontais
plt.figure(figsize=(12,8))
sns.barplot(x=correlacao.values, y=correlacao.index)

# Configurando os limites do eixo x
plt.xlim(0, 2)

# Exibindo o gráfico
plt.show()

print(tabela.columns)

display(tabela)

# Calculando a correlação das colunas em relação à coluna 'Categoria'
correlacao = tabela.corr()['Categoria'].sort_values()

# Criando o gráfico de barras horizontais
plt.figure(figsize=(16,8))
sns.barplot(x=correlacao.values, y=correlacao.index)
plt.xlim(-1, 1)
plt.show()

display(tabela)

# Para cada coluna, criamos um gráfico de caixa
for coluna in tabela.columns:
    if coluna != 'Categoria':
        plt.figure(figsize=(12,6))
        sns.boxplot(x='Categoria', y=coluna, data=tabela)
        plt.title('Influência da coluna ' + coluna)
        plt.show()

# Grava o arquivo com as alterações
tabela.to_csv("arquivo.csv", index=False)

